# Generated by Django 2.0.5 on 2019-07-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('company_name', models.CharField(default='', max_length=100000)),
                ('sector', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
                ('about_company', models.CharField(max_length=1000)),
            ],
        ),
    ]
