# Generated by Django 2.0.5 on 2019-07-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_email', models.CharField(max_length=100)),
                ('company_name', models.CharField(default='', max_length=100000)),
            ],
        ),
    ]
