# Generated by Django 2.0.5 on 2019-08-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recruiters'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
