# Generated by Django 2.0.5 on 2019-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='company_name',
            field=models.CharField(default='1', max_length=100000),
        ),
        migrations.AlterField(
            model_name='user_id',
            name='idd',
            field=models.IntegerField(default=1),
        ),
    ]
